one/app1/urls.py
from django.conf.urls import url
from .views import PostList, post_detail

urlpatterns = [
    url(r'ˆ$', PostList.as_view(), {'parent_template': 'base.html'}, name='app1_post_list'),
    url(r'ˆ(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        post_detail, name='app1_post_detail'),
]

one/one/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url


from organizer import urls as organizer_urls
from app1 import urls as app1_urls
from .views import redirect_root


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include(organizer_urls)),
    re_path('ˆblog/', include(app1_urls)),
    url(r'^$', redirect_root),
]

one/organizer/urls.py
from django.conf.urls import url, re_path
from django.urls import path

from .views import homepage, tag_detail, startup_list, startup_detail, tag_list

urlpatterns = [

    url(r'^startup/(?P<slug>[\w\-]+)/$', startup_detail, name='organizer_startup_detail'),
    url(r'^startup/$', startup_list, name='organizer_startup_list'),
    url(r'^$', homepage),
    url(r'^tag/$', tag_list, name='organizer_tag_list'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', tag_detail, name='organizer_tag_detail')

]

one/app1/models.py
from django.db import models
from organizer.models import Tag, Startup
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=60, help_text='A label for URL config', unique_for_month='pub_date')
    text = models.TextField()
    pub_date = models.DateField('date published', auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name='blog_posts')
    startups = models.ManyToManyField(Startup, related_name='blog_posts')

    def get_absolute_url(self):
        return reverse('app1_post_detail', kwargs={'year': self.pub_date.year,'month': self.pub_date.month,'slug': self.slug})

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.title

one/organizer/models.py
from django.db import models
from django.urls import reverse

class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True, help_text='A label for URL config.')

    def get_absolute_url(self):
        return reverse('organizer_tag_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name.title()


class Startup(models.Model):
    name = models.CharField(max_length=30, db_index=True)
    slug = models.SlugField(max_length=30, unique=True, help_text='A label for URL config.')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)

    def get_absolute_url(self):
        return reverse('organizer_startup_detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

    def __str__(self):
        return self.name


class NewsLink(models.Model):
    title = models.CharField(max_length=60)
    pub_date = models.DateField('date published')
    link = models.URLField()
    startup = models.ForeignKey(Startup, on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

    def __str__(self):
        return "{} : {}" .format(self.startup, self.title)

one/app1/forms.py
from django import forms
from .models import Post, Startup, Tag


class PostForm(forms.ModelForm):
    class Meta:
        model = 'Post'
        fields = '__all__'

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

one/organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Tag, Startup, NewsLink


class SlugCleanMixin:
    def clean_slug(self):
        new_slug = (self.cleaned_data['slug'].lower())
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create".')
        return new_slug


class TagForm(forms.ModelForm, SlugCleanMixin):
    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()


class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = 'NewsLink'
        fields = '__all__'


class StartupForm(forms.ModelForm, SlugCleanMixin):
    class Meta:
        model = 'NewsLink'
        fields = '__all__'

one/app1/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Tag, Post
from django.views.generic import View


def homepage(request):
    tag_list = Tag.objects.all()
    output = ", ".join([tag.name for tag in tag_list])
    return HttpResponse(output)

class PostList(View):
    template_name = 'app1/post_list.html'
    def get(self, request, parent_template=None):
        return render(request, self.template_name, {'post_list': Post.objects.all()})

def post_detail(request, year, month, slug, parent_template=None):
    post = get_object_or_404(Post, pub_date__year=year, pub_date__month=month, slug=slug)
    return render(request, 'app1/post_detail.html', {'post': post, 'parent_template': parent_template})

one/one/views.py
from django.shortcuts import redirect


def redirect_root(request):
    return redirect('app1_post_list')

one/organizer/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader, RequestContext
from django.http.response import HttpResponse

from .models import Tag, Startup


def homepage(resuest):
    return render(resuest, 'organizer/tag_list.html', {'tag_list': Tag.objects.all()})


def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    return render(request, 'organizer/tag_detail.html', {'tag': tag})


def tag_list(request):
    return render(request, 'organizer/tag_list.html', {'tag_list': Tag.objects.all()})


def startup_list(request):
    return render(request, 'organizer/startup_list.html', {'startup_list': Startup.objects.all()})


def startup_detail(request):
    return render(request, 'organizer/startup_detail.html', {'startup': Startup})

one/app1/templates/app1/base_app1.html
{% extends parent_template|default:"base.html" %}

one/app1/templates/app1/post_detail.html
+<article>
+
+    <header>
+      <h2>{{ post.title|title }}</h2>
+      <p>
+        Written on
+        <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
+          {{ post.pub_date|date:"l, F j, Y" }}
+        </time>
+      </p>
+    </header>
+
+    {{ post.text|linebreaks }}
+
+  {% if post.startups.all or post.tags.all %}
+    <footer>
+
+      {% if post.startups.all %}
+          <section>
+            <h3>Startup{{ post.startups.count|pluralize }}</h3>
+            <ul>
+              {% for startup in post.startups.all %}
+                <li><a href="">
+                  {{ startup.name }}
+                </a></li>
+              {% endfor %}
+            </ul>
+          </section>
+      {% endif %}
+
+      {% if post.tags.all %}
+          <section>
+            <h3>Tag{{ post.tags.count|pluralize }}</h3>
+            <ul>
+              {% for tag in post.tags.all %}
+                <li><a href="">
+                  {{ tag.name|title }}
+                </a></li>
+              {% endfor %}
+            </ul>
+          </section>
+      {% endif %}
+
+    </footer>
+  {% endif %}
+
+</article>

one/app1/templates/app1/post_list.html
{% for post in post_list %}
    <article>
         <header>
            <h2>
                <a href="">
                     {{ post.title|title }}</a>
            </h2>
             <p>
                Written on:
                <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                    {{ post.pub_date|date:"l, F j, Y" }}
                 <a href="{{ post.get_absolute_url }}">
                 {{ post.title|title }}</a>
                </time>
             </p>
         </header>
        <p>{{ post.text|truncatewords:20 }}</p>
        <p>
            <a href="{{ post.get_absolute_url }}">
                Read more&hellip;</a>
        </p>
    </article>
 {% empty %}
 <p><em>No Blog Posts Available</em></p>
 {% endfor %}

one/organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

one/organizer/templates/organizer/post_detail.html
+<article>
+
+    <header>
+      <h2>{{ post.title|title }}</h2>
+      <p>
+        Written on
+        <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
+          {{ post.pub_date|date:"l, F j, Y" }}
+        </time>
+      </p>
+    </header>
+
+    {{ post.text|linebreaks }}
+
+  {% if post.startups.all or post.tags.all %}
+    <footer>
+
+      {% if post.startups.all %}
+          <section>
+            <h3>Startup{{ post.startups.count|pluralize }}</h3>
+            <ul>
+              {% for startup in post.startups.all %}
+                <li><a href="">
+                  {{ startup.name }}
+                </a></li>
+              {% endfor %}
+            </ul>
+          </section>
+      {% endif %}
+
+      {% if post.tags.all %}
+          <section>
+            <h3>Tag{{ post.tags.count|pluralize }}</h3>
+            <ul>
+              {% for tag in post.tags.all %}
+                <li><a href="">
+                  {{ tag.name|title }}
+                </a></li>
+              {% endfor %}
+            </ul>
+          </section>
+      {% endif %}
+
+    </footer>
+  {% endif %}
+
+</article>

one/organizer/templates/organizer/startup_detail.html
 <article>

   <h2>{{ startup.name }}</h2>
   <dl>
     <dt>Date Founded</dt>
       <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
     <dt>Website</dt>
       <dd>{{ startup.website|urlize }}</dd>
     <dt>Contact</dt>
       <dd>{{ startup.contact }}</dd>

       <dt>Tag{{ startup.tags.count|pluralize }}</dt>
         {% for tag in startup.tags.all %}
           <dd><a href="">
             {{ tag.name|title }}
           </a></dd>
         {% endfor %}

   </dl>

-  <p>{{ startup.description }}</p>
+  {{ startup.description|linebreaks }}

       {% if startup.newslink_set.all %}
           <section>
             <h3>Recent News</h3>
             <ul>
               {% for newslink in startup.newslink_set.all %}
                 <li>
                   <a href="{{ newslink.link }}">
                     {{ newslink.title|title }}</a>
                 </li>
               {% endfor %}
             </ul>
           </section>
       {% endif %}

       {% if startup.blog_posts.all %}
           <section>
             <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
             <ul>
               {% for post in startup.blog_posts.all %}
                 <li>
                   <a href="">
                    {{ post.title|title }}</a>
+                </li>
+              {% endfor %}
+            </ul>
+          </section>
+      {% endif %}
+
+</article>

one/organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

 {% block title %}
 {{ block.super }} - Startups
 {% endblock %}

{% block content %}
    <h2>Startup List</h2>
     <ul>
     {% for startup in startup_list %}
       <li>
        <a href="{{ startup.get_absolute_url }}">
           {{ startup.name }}</a>
       </li>
     {% empty %}
            <li><em>No Startups Available</em></li>
        {% endfor %}
     </ul>
{% endblock %}

one/organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
<h2>{{ tag.name|title }}</h2>
   {% if tag.startup_set.all %}
     <section>
+      <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
       <p>
         Tag is associated with
         {{ tag.startup_set.count }}
         startup{{ tag.startup_set.count|pluralize }}.
       </p>
       <ul>
         {% for startup in tag.startup_set.all %}
           <li><a href="">
             {{ startup.name }}
           </a></li>
         {% endfor %}
       </ul>
     </section>
   {% endif %}
       {% if tag.app1_posts.all %}
         <section>
-          <h3>Blog Posts</h3>
+          <h3>Blog Post{{ tag.app1_posts.count|pluralize }}</h3>
           <ul>
             {% for post in tag.app1_posts.all %}
               <li><a href="">
                 {{ post.title|title }}
               </a></li>
             {% endfor %}
           </ul>
         </section>
       {% endif %}
       {% if not tag.startup_set.all and not tag.app1_posts.all %}
         <p>This tag is not related to any content.</p>
{% endif %}

one/organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
  <form
    action="{% url 'organizer_tag_create' %}"
    method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
      {{ form.name.errors }}
     <p>
       <label for="{{ form.name.id_for_label }}">
      {{ form.name.label }}:
       </label>
        {{ form.name }}
     </p>
     {{ form.slug.errors }}
     <p>
       <label for="{{ form.slug.id_for_label }}">
     {{ form.slug.label }}:
       </label>
      {{ form.slug }}
       <span class="helptext">
        {{ form.slug.help_text }}
       </span>
     </p>
     <button type="submit">
       Create Tag</button>
   </form>
{% endblock %}

one/organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block content %}
   <h2>Tag List</h2>
   <ul>
     {% for tag in tag_list %}
       <li>
         <a href="{{ tag.get_absolute_url }}">
           {{ tag.name|title }}</a>
       </li>
     {% empty %}
       <li><em>There are currently no Tags available.</em></li>
     {% endfor %}
   </ul>
{% endblock %}

one/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        Startup Organizer
        {% endblock %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <div><!-- container -->
      <header>
          <h1>Startup Organizer</h1>
      </header>
      <nav>
        <ul>
            <a href="{% url 'app1_post_list' %}">
              Blog</a></li>
          <li>
            <a href="{% url 'organizer_startup_list' %}">
              Startups</a></li>
          <li>
            <a href="{% url 'organizer_tag_list' %}">
              Tags</a></li>

        </ul>
      </nav>
      <main>
          {% block content %}
          This is default content!
          {% endblock %}
      </main>
    </div><!-- container -->

    <footer>
      <p>
        &copy; 2015
        <a href="https://AndrewsForge.com/">
          Andrew Pinkham</a>
      </p>
      <p>
        Created for
        <a href="https://Django-Unleashed.com/">
          Django Unleashed</a>
      </p>
    </footer>

  </body>

</html>